### ISSUE TITLE
Edit instructions "visit http://localhost:8080/marmotta"

### ISSUE THREAD

**Issue by keski** [nicholsn/docker-marmotta#1]
The instruction should be updated for users that don't run docker on Linux. The correct IP can be found using:

``` bash
$ docker-machine ip default
192.168.99.100
```

**Comment by keski** [comment]
This seems to be related to a more general issue as well: it will only run on Linux due to explicit references to localhost in several places.

**Comment by nicholsn** [comment]
Thank for your feedback, @keski. I've updated the instructions to use `docker-machine ip <name-of-vm>` rather than localhost.

This container works on linux and mac. If you would like to extend it to work on windows, please submit a PR and I'll be happy to review and merge.
